language: node_js
node_js:
  - "10.21.0"

addons:
  chrome: stable

before_script:
  - npm install -g @angular/cli@8.3.25

jobs:
  include:
    - stage: test
      name: "Add and Remove Friend"
      script: ng e2e --protractor-config='e2e/src/desktop/add-and-remove-restvo-friend.conf.js'
    - name: "Create and Delete a Community"
      script: ng e2e --protractor-config='e2e/src/desktop/create-delete-community.conf.js'
    - name: "Join Journey Test"
      script: ng e2e --protractor-config='e2e/src/desktop/journey.conf.js'
    - name: "Add User to Group"
      script: ng e2e --protractor-config='e2e/src/desktop/add-user-to-group.conf.js'
    - name: "Register New Account Test"
      script: ng e2e --protractor-config='e2e/src/desktop/register.conf.js'
    - name: "Tab Navigation Test"
      script: ng e2e --protractor-config='e2e/src/mobile/tab-navigate.conf.js'

