platform :ios, '11'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorJitsiMeet', :path => '../../node_modules/capacitor-jitsi-meet'
  pod 'CapacitorShareExtension', :path => '../../node_modules/capacitor-share-extension'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
  if target.name == 'CapacitorJitsiMeet' || target.name == 'CapacitorJitsiMeet-Plugin'
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  end
end
